"""add chunks table

Revision ID: 7938b67b66cb
Revises: 0270525ebbe2
Create Date: 2026-08-12 07:32:20.283805

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7938b67b66cb"
down_revision: Union[str, Sequence[str], None] = "0270525ebbe2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
